### ISSUE TITLE
前端笔记之CSS

### ISSUE THREAD

**Issue by wxiubin** [sanyucz/iOSNote#2]
CSS 全称是**Cascading Style Sheets**，层叠样式表，被用来控制HTML标签的样式，美化网页
。CSS有两个重点： **属性** 和 **选择器** 。

#### CCS的编写格式

CCS的编写格式是以键值对的形式，如：

```css
color : red;
background-color : blue;
font-size : 20px;
```

* 属性一般由属性名和属性值组成，左边是属性名，右边是属性的值

#### CSS有3种书写形式：

1. 行内样式：（内联样式）直接在标签的 **style** 属性中书写

```css
<body style="color : red;">
```

2. 页内样式：在本网页的 **style**标签中书写

```css
<style>
<body {
color : red;
}
</style>
```

3. 外部样式：在单独的CSS文件中书写，然后在网页中用link引入

```css
<link rel="stylesheet" href="index.css">
```

##### 1. 标签选择器

根据标签名查找标签：

```css
<div>div1<div>
```

找到标签，设置样式：

```css
div {
color : red;
}
```

##### 2. 类选择器

```css
<p class="high">hello world</>
```
```css
.high{
color : red;
}
```

##### 3. id选择器

```css
<p id="first">Hello world</p>
```
```css
#first{
color : red;
}
```

##### 4. 并列选择器

```css
<div class="high">div high</div>
<div class="low">div low</div>
<p class="high">p high</p>
<p class="low">p low</p>
```

```css
div, .high{
color : red;
}
```

并列选择，只要一个符合条件就可以
结果：

<div style="text-align:center;background-color:lightgray" >
<font color=red>div high</font><br>
<font color=red>div low</font><br>
<font color=red>p high</font><br>
<font color=black>p low</font><br>
</div>

##### 5. 复合选择器

```css
<div class="high">div high</div>
<div class="low">div low</div>
<p class="high">p high</p>
<p class="low">p low</p>
```
```css
div .high{
color : red;
}
```

复合选择，必须全部符合条件就可以
结果：

<div style="text-align:center;background-color:lightgray" >
<font color=red>div high</font><br>
<font color=black>div low</font><br>
<font color=black>p high</font><br>
<font color=black>p low</font><br>
</div>

##### 6. 后代选择器

```css
<div>
<p>div -> p</p>
<span>
<p>div -> span -> p</p>
</span>
</div>
<p>div p</p>
```
```css
div p {
color : red;
}
```

只要是在**div** 里面的 **p** 标签，都符合要求，结果：

<div style="text-align:center;background-color:lightgray" >
<font color=red>div -> p</font><br>
<font color=red>div -> span -> p</font><br>
<font color=black>div p</font><br>
</div>

##### 7. 直接后代选择器

```css
<div>
<p>div -> p</p>
<span>
<p>div -> span -> p</p>
</span>
</div>
```
```css
div p {
color : red;
}
```

必须是直接在**div** 里面的 **p** 标签，才符合要求，即儿子可以，孙子就不行
结果：

<div style="text-align:center;background-color:lightgray" >
<font color=red>div -> p</font><br>
<font color=black>div -> span -> p</font><br>
</div>

##### 8. 相邻兄弟选择器

```css
<div>
<p>div -> p</p>
<span>
<p>div -> span -> p</p>
</span>
</div>
<p>div p</p>
<p>p p</p>
```
```css
div + p {
color : red;
}
```

只要是在**div** 里面的 **p** 标签，都符合要求，结果：

<div style="text-align:center;background-color:lightgray" >
<font color=black>div -> p</font><br>
<font color=black>div -> span -> p</font><br>
<font color=red>div p</font><br>
<font color=black>p p</font><br>
</div>

##### 9. 属性选择器

```css
<div name="Jack">name = Jack</div>
<div name="Tom">name = Tom</div>
<div name="Bob" age="20">name = Bob, age = 20</div>
<div>no name</div>
```
```css
div[name] {
color : red;
}
div[name][age] {
color : green;
}
div[name="Tom"] {
color : yellow;
}
```

<div style="text-align:center;background-color:lightgray" >
<font color=red>name = Jack</font><br>
<font color=yellow>name = Tom</font><br>
<font color=green>name = Bob, age = 20</font><br>
<font color=black>no name</font><br>
</div>

##### 10. 伪类
属性 | 描述
--------- | ----------
:active | 向被激活的的元素添加样式
... | ...

##### 11. 伪元素

...

#### 选择器优先级

选择器针对性越强、范围越小，优先级就越高
选择器的权值：

选择器 | 权值
--------- | ----------
通配符 | 0
标签 | 1
类 | 10
属性 | 10
伪类 | 10
id | 100
important | 1000

* 原则：选择器的权值加在一起，大的优先，权值一样，后定义的优先
